### ISSUE TITLE
Asking for permission to copy this repository 

### ISSUE THREAD

**Issue by teimor** [korzhyk/OpenCore_GA-H97M-D3H#1]
Hi,

I would like to copy, update & publish this repository with some changes and additional information for `GA-H97-D3H-CF` motherboard and RX580 card. Due that `GA-H97-D3H-CF` motherboard with current setup will have some issues with sleep and also decoding issues with dGPU.

So I'm asking your permission to copy (not fork it due that I will change some things and file structure) and republish it with credit for you support. 

Thanks.

**Comment by korzhyk** [comment]
@teimore oh, yes you can copy. Issues with dGPU is predictable but what the problem with sleep?

**Comment by teimor** [comment]
Thanks for the approval. The problem with sleep that after sleep the system gets an kernel panic and black screen. After some research it caused by Serial Port A of iTE I/O Controller Chip. In order to fix it need to change one bios settings: `Peripherals → Super IO Configuration → Serial Port A → Disabled`
